# Generated by Django 6.0.7 on 2026-07-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_permission"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_user_per_tenant",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="role",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="user",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
