# Generated by Django 6.0.7 on 2026-07-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "company_mobile",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "company_email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("database_alias", models.CharField(db_index=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="tenants_name_bc4541_idx")
                ],
            },
        ),
    ]
