# Generated by Django 6.0.7 on 2026-07-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["name"],
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["name"], name="tenants_name_bc4541_idx"),
        ),
        migrations.AlterModelTable(
            name="tenant",
            table="tenants",
        ),
    ]
