# Generated by Django 6.0.7 on 2026-07-27 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
        ("tenants", "0003_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="rbac.role",
            ),
        ),
    ]
