# Generated by Django 6.0.7 on 2026-09-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                ("deal_code", models.CharField(db_index=True, max_length=30)),
                ("customer_id", models.PositiveBigIntegerField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("QUALIFICATION", "Qualification"),
                            ("PROPOSAL", "Proposal"),
                            ("NEGOTIATION", "Negotiation"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                        ],
                        default="QUALIFICATION",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("WON", "Won"), ("LOST", "Lost")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                (
                    "probability",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "deals",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "deal_code"],
                        name="deals_tenant__0d510b_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "customer_id"],
                        name="deals_tenant__13e520_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "stage"], name="deals_tenant__becf02_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "status"], name="deals_tenant__6b4fd1_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "title"], name="deals_tenant__c78ce8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "deal_code"),
                        name="unique_deal_code_per_tenant",
                    )
                ],
            },
        ),
    ]
