# Generated by Django 6.0.7 on 2026-09-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                ("product_code", models.CharField(db_index=True, max_length=30)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("GOODS", "Goods"), ("SERVICE", "Service")],
                        default="GOODS",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("unit", models.CharField(default="PCS", max_length=50)),
                ("hsn_code", models.CharField(blank=True, max_length=20)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "product_code"],
                        name="products_tenant__356e76_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "name"], name="products_tenant__67a8c7_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "sku"], name="products_tenant__3575bc_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "product_code"),
                        name="unique_product_code_per_tenant",
                    )
                ],
            },
        ),
    ]
