# Generated by Django 6.0.7 on 2026-09-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                ("quote_code", models.CharField(db_index=True, max_length=30)),
                ("customer_id", models.PositiveBigIntegerField(db_index=True)),
                (
                    "deal_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "quotes",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "quote_code"],
                        name="quotes_tenant__c3b878_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "customer_id"],
                        name="quotes_tenant__7f3ced_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "deal_id"],
                        name="quotes_tenant__ba1626_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "status"], name="quotes_tenant__0da070_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "quote_code"),
                        name="unique_quote_code_per_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quote_id", models.PositiveBigIntegerField(db_index=True)),
                ("product_id", models.PositiveBigIntegerField(db_index=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "line_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "quote_items",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["quote_id"], name="quote_items_quote_i_98cf8f_idx"
                    ),
                    models.Index(
                        fields=["product_id"], name="quote_items_product_425fc4_idx"
                    ),
                ],
            },
        ),
    ]
