# Generated by Django 5.2.16 on 2026-08-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='Module',
        ),
        migrations.RemoveConstraint(
            model_name='permission',
            name='unique_resource_permission_type',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='resource',
            new_name='module',
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('module', 'permission_type'), name='unique_module_permission_type'),
        ),
        migrations.AlterModelTable(
            name='module',
            table='modules',
        ),
    ]
