# Generated by Django 6.0.7 on 2026-07-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="tenant",
        ),
        migrations.RemoveConstraint(
            model_name="rolepermission",
            name="unique_role_permission",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="role",
        ),
    ]
