# Generated by Django 6.0.7 on 2026-07-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_remove_role_tenant_and_more"),
        ("tenants", "0004_alter_membership_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="RolePermission",
        ),
    ]
