# Generated by Django 6.0.7 on 2026-07-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                ("customer_code", models.CharField(db_index=True, max_length=30)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("BUSINESS", "Business"),
                        ],
                        default="BUSINESS",
                        max_length=20,
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("gst_number", models.CharField(blank=True, max_length=20)),
                ("pan_number", models.CharField(blank=True, max_length=20)),
                ("remarks", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customers",
                "ordering": ["contact_name"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "customer_code"],
                        name="customers_tenant__4ae6b0_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "customer_code"),
                        name="unique_customer_code_per_tenant",
                    ),
                    models.UniqueConstraint(
                        fields=("tenant_id", "gst_number"),
                        name="unique_customer_gst_per_tenant",
                    ),
                ],
            },
        ),
    ]
