# Generated by Django 5.2.16 on 2026-08-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('gst_number__isnull', False)), fields=('tenant_id', 'gst_number'), name='unique_customer_gst_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('pan_number__isnull', False)), fields=('tenant_id', 'pan_number'), name='unique_customer_pan_per_tenant'),
        ),
    ]
