# Generated by Django 5.2.16 on 2026-08-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_unique_customer_gst_per_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
