# Generated by Django 5.2.16 on 2026-08-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_gst_number_alter_customer_pan_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_gst_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_pan_per_tenant',
        ),
    ]
