# Generated by Django 6.0.7 on 2026-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                ("vendor_code", models.CharField(db_index=True, max_length=30)),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("BUSINESS", "Business"),
                        ],
                        default="BUSINESS",
                        max_length=20,
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("gst_number", models.CharField(blank=True, max_length=20)),
                ("pan_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("remarks", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vendors",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "vendor_code"],
                        name="vendors_tenant__a14c58_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "contact_name"],
                        name="vendors_tenant__f232b0_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "company_name"],
                        name="vendors_tenant__84dfed_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "vendor_code"),
                        name="unique_vendor_code_per_tenant",
                    )
                ],
            },
        ),
    ]
