# Generated by Django 6.0.7 on 2026-08-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                (
                    "sequence_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("VENDOR", "Vendor"),
                            ("PRODUCT", "Product"),
                            ("SALES_ORDER", "Sales Order"),
                            ("PURCHASE_ORDER", "Purchase Order"),
                            ("INVOICE", "Invoice"),
                        ],
                        max_length=50,
                    ),
                ),
                ("next_number", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sequences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "sequence_type"),
                        name="unique_sequence_per_tenant",
                    )
                ],
            },
        ),
    ]
