# Generated by Django 6.0.7 on 2026-08-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequence",
            name="sequence_type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("LEAD", "Lead"),
                    ("VENDOR", "Vendor"),
                    ("PRODUCT", "Product"),
                    ("SALES_ORDER", "Sales Order"),
                    ("PURCHASE_ORDER", "Purchase Order"),
                    ("INVOICE", "Invoice"),
                ],
                max_length=50,
            ),
        ),
    ]
