# Generated by Django 6.0.7 on 2026-08-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                ("lead_code", models.CharField(db_index=True, max_length=30)),
                ("contact_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "Website"),
                            ("REFERRAL", "Referral"),
                            ("SOCIAL_MEDIA", "Social Media"),
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("QUALIFIED", "Qualified"),
                            ("LOST", "Lost"),
                            ("CONVERTED", "Converted"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "leads",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "lead_code"],
                        name="leads_tenant__1040d7_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "status"], name="leads_tenant__ffb606_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "contact_name"],
                        name="leads_tenant__95445e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "lead_code"),
                        name="unique_lead_code_per_tenant",
                    )
                ],
            },
        ),
    ]
